### ISSUE TITLE
trial list on voxceleb2

### ISSUE THREAD

**Issue by PeiwenSun2000** [czy97/Voxceleb1-missing-cropped-face-images#1]
I have noticed that your work used your own costumized trial list on voxceleb2.
Can you offer me such list?
It will be of great help.
Looking forward your reply.

**Comment by czy97** [comment]
> I have noticed that your work used your own costumized trial list on voxceleb2. Can you offer me such list? It will be of great help. Looking forward your reply.

You can download it using this link: https://swshon.github.io/supplement/noise_tolerent/voxceleb2_trials

**Comment by PeiwenSun2000** [comment]
Thank you a lot.
